name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pipx install uv

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .[dev]

      - name: Lint (Ruff) and Format (Black --check)
        run: |
          ruff check .
          black --check .

      - name: Type check (mypy --strict)
        run: |
          mypy --strict

      - name: Run tests with coverage
        run: |
          mkdir -p test-reports coverage/html
          pytest -q

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/coverage.xml
            coverage/html/

